# Generated by Django 6.0.3 on 2026-03-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(default='expert', max_length=10),
        ),
    ]
