# Generated by Django 6.0.3 on 2026-03-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_userprofile_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('expert', 'Expert Pro'), ('startup', 'Startup'), ('business', 'Business')], default='starter', max_length=10),
        ),
    ]
