# Generated by Django 6.0.2 on 2026-03-05 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('expert', 'Expert'), ('startup', 'Startup')], max_length=10)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_clv', models.FloatField()),
                ('churn_rate', models.FloatField()),
                ('roi_potential', models.FloatField()),
                ('top_city', models.CharField(max_length=100)),
                ('data_json', models.JSONField()),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='analysis.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='analysis.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
                ('count', models.IntegerField()),
                ('rfm_r', models.FloatField()),
                ('rfm_f', models.FloatField()),
                ('rfm_m', models.FloatField()),
                ('clv', models.FloatField()),
                ('description', models.TextField()),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='analysis.analysis')),
            ],
        ),
    ]
