# Generated by Django 6.0.3 on 2026-03-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersegment',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
