# Generated by Django 6.0.3 on 2026-03-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_analysis_result_data_customersegment_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersegment',
            name='clv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customersegment',
            name='rfm_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customersegment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
